version: '3.2'
services:
  dal-php:
    build:
      context: ./
      dockerfile: Dockerfile
    image: dal-php
    volumes:
      - ./:/dal:delegated

  dal-postgresql-test:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD:    "secret"
      POSTGRES_INITDB_ARGS: "--locale=en_US.UTF-8"
    hostname: postgresql-test
    volumes:
      - ./tests/data/:/docker-entrypoint-initdb.d/